namespace: cf-stocks
stacker_bucket_region: us-west-2
sys_path: ./

stacks:
  - name: shared
    class_path: shared.Stocks
    variables:
      env-dict:
        BucketName: stocks-shared-bucket

  - name: api
    class_path: api.Stocks
    variables:
        env-dict:
          ApiName: stocks-api-gateway

  - name: lambdas
    class_path: lambdas.Stocks
    variables:
        env-dict:
          BucketName: stocks-shared-bucket
          StocksPatternLambdaName: stocks-pattern-lambda
          SharedSecretsId: stocks/shared/secrets
  
  - name: jobs
    class_path: jobs.Stocks
    variables:
        env-dict:
          BucketName: stocks-shared-bucket
          OrderSyncLambdaName: stocks-order-sync-lambda
          ProfitCalculatorLambdaName: stocks-profit-calculator-lambda
          CancelOrdersLambdaName: stocks-cancel-lambda
          SharedSecretsId: stocks/shared/secrets

  - name: integrations
    class_path: integrations.Stocks
    variables:
        env-dict:
          ApiKeyName: StocksApiKey
          ApiUsagePlanName: StocksApiUsagePlan
